// AUTO-GENERATED by scripts/gen-theme.mjs from src/theme.config.mjs. Do not edit by hand.
// Edit colors in src/theme.config.mjs, then run `npm run gen:theme`.

export const brand = {
  "50": "#E1F6FB",
  "100": "#C4EAF5",
  "200": "#A3D8E8",
  "300": "#82C3D6",
  "400": "#5FAEC2",
  "500": "#3996AE",
  "600": "#24839A",
  "700": "#046A82",
  "800": "#035065",
  "900": "#023944",
  "950": "#01151F",
} as const;

export const accent = {
  "50": "#ECFEFF",
  "100": "#CFFAFE",
  "200": "#A5F3FC",
  "300": "#67E8F9",
  "400": "#22D3EE",
  "500": "#06B6D4",
  "600": "#0891B2",
  "700": "#0E7490",
  "800": "#155E75",
  "900": "#164E63",
  "950": "#083344",
} as const;

/** Editor canvas overlay colors (React-rendered SVG/CSS overlays; the engine
 *  cannot read CSS, so these are imported as data). `selection` is a
 *  deliberate cool hue kept distinct from the brand so selections stay
 *  legible against brand-colored content. */
export const overlay = {
  selection: "#2563eb",
  guideSubtle: "#3b82f6",
  guideActive: "#06b6d4",
  guideConflict: "#f43f5e",
  penPreview: "#a855f7",
  ruler: "#9ca3af",
} as const;

/** Collaborator presence palette (assigned by a stable hash; shared with the
 *  Go backend via presence_palette_gen.go). */
export const presencePalette = [
  "#ef4444",
  "#f97316",
  "#eab308",
  "#22c55e",
  "#06b6d4",
  "#3b82f6",
  "#8b5cf6",
  "#ec4899",
  "#14b8a6",
  "#a855f7",
] as const;
export const presenceFallback = "#ef4444";

/** Avatar swatches (a distinct rainbow for telling collaborators apart). */
export const avatarColors = [
  "#e11d48",
  "#ea580c",
  "#d97706",
  "#16a34a",
  "#0891b2",
  "#2563eb",
  "#7c3aed",
  "#db2777",
] as const;
